blank_issues_enabled: true
contact_links:
  - name: SpikeInterface
    url: https://github.com/SpikeInterface/spikeinterface
    about: The sister project for reading from extracellular electrophysiology data formats.
  - name: NeuroConv
    url: https://github.com/catalystneuro/neuroconv
    about: Convenient package used for writing any ROI Extractor object to the Neurodata Without Borders (NWB) format.
