name: Deploy PR Tests

on:
  workflow_dispatch:
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    run-tests:
        uses: ./.github/workflows/run-tests.yml
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            S3_GIN_BUCKET: ${{ secrets.S3_GIN_BUCKET }}

    dev-tests:
        uses: ./.github/workflows/dev-testing.yaml
        secrets:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            S3_GIN_BUCKET: ${{ secrets.S3_GIN_BUCKET }}
