name: Deploy PR Tests

on:
  workflow_dispatch:
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    update-testing-data:
        uses: ./.github/workflows/update-testing-data.yml

    run-tests:
        needs: update-testing-data
        uses: ./.github/workflows/run-tests.yml

    dev-tests:
        needs: update-testing-data
        uses: ./.github/workflows/dev-testing.yaml
