name: Deploy PR Tests

on:
  workflow_dispatch:
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    run-tests:
        uses: ./.github/workflows/run-tests.yml
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

    dev-tests:
        uses: ./.github/workflows/dev-testing.yaml
