name: Detect Changelog Updates
on:
  pull_request:
  workflow_dispatch:

jobs:
  assess-file-changes:
    uses: ./.github/workflows/assess-file-changes.yml

  detect-changelog-updates:
    needs: assess-file-changes
    if: ${{ needs.assess-file-changes.outputs.SOURCE_CHANGED == 'true' }}
    name: Auto-detecting CHANGELOG.md updates
    runs-on: ubuntu-latest
    steps:
      - if:  ${{ needs.assess-file-changes.outputs.CHANGELOG_UPDATED == 'true' }}
        run: echo "CHANGELOG.md has been updated."
      - if:  ${{ needs.assess-file-changes.outputs.CHANGELOG_UPDATED == 'false' }}
        run: |
          echo "CHANGELOG.md has not been updated."
          0
