name: Dev Testing
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      S3_GIN_BUCKET:
        required: true

jobs:
  run:
    name: Ubuntu tests with Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - run: git fetch --prune --unshallow --tags
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Global Setup
        run: |
            pip install -U pip
            git config --global user.email "CI@example.com"
            git config --global user.name "CI Almighty"

      - name: Install full requirements
        run: |
            pip install .[test,full]

      - name: Clone and Install NeuroConv
        run: |
            git clone https://github.com/catalystneuro/neuroconv.git
            cd neuroconv
            pip install --no-cache-dir .[full,test]
            cd ../
      - name: Prepare data for tests
        uses: ./.github/actions/load-data
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          s3-gin-bucket: ${{ secrets.S3_GIN_BUCKET }}

      - name: Run NeuroConv tests
        run: |
            pytest -n auto --dist loadscope neuroconv/tests/test_modalities/test_ophys neuroconv/tests/test_on_data/ophys/test_imaging_interfaces.py neuroconv/tests/test_on_data/ophys/test_segmentation_interfaces.py
